return {
    enable = true,
    max_lines = 0,
    trim_scope = 'outer',
    min_window_height = 0,
    patterns = {
        default = {
            'class',
            'function',
            'method',
            'for',
            'while',
            'if',
            'switch',
            'case',
            'interface',
            'struct',
            'enum',
        },
        zig = {
            'block',
            'FnProto',
            'function',
            'TopLevelDecl',
            'Statement',
            'IfStatement',
            'WhileStatement',
            'WhileExpr',
            'ForStatement',
            'ForExpr',
            'WhileStatement',
            'WhileExpr',
        },
    },
}
